### ISSUE TITLE
Can anyone train on your own data well?

### ISSUE THREAD

**Issue by heyulinxp** [MarvinTeichmann/KittiSeg#38]
I want to train this model on my own data, which is collected from the camera in our car. After I label these pictures with "road_color" and “background_color",and then I try to use train.py. However, in ./RUN/**/image , the test image always perform badly. I want to ask , has anyone successfully trained his own model on his own data?
In some images in ./DATA/data_road/training/gt_image_2, I found some black blocks in these images.  I know [255,0,255] means road_color, and [255,0,0] means background_color. What does these black blocks means?
Thanks for help~

**Comment by StuvX** [comment]
I haven't been able to get my images to train, because my computer runs out of memory - but the black blocks mean don't use this data to train, effectively where it's hard to tell whether it's road or not - you can use any color other than [255,0,255] and [255,0,0] but Marvin used black to easily show these areas.

**Comment by heyulinxp** [comment]
Oh, thanks. I notice that the black blocks Marvin used usually mean the curb.
Now I can train my images since I change some parameters, and it performs well......
