### ISSUE TITLE
What does gt_zero do in resize_label_image()? 

### ISSUE THREAD

**Issue by villanuevab** [MarvinTeichmann/KittiSeg#72]
In `inputs/kitti_seg_input.py` there is a function for resizing the image and its corresponding gt_image. What is the purpose of `gt_zero` here? And what is the purpose of dividing the resized image pixels by 255?
```
def resize_label_image(image, gt_image, image_height, image_width):
    image = scipy.misc.imresize(image, size=(image_height, image_width),
                                interp='cubic')
    shape = gt_image.shape
    gt_zero = np.zeros([shape[0], shape[1], 1])
    gt_image = np.concatenate((gt_image, gt_zero), axis=2)
    gt_image = scipy.misc.imresize(gt_image, size=(image_height, image_width),
                                   interp='nearest')
    gt_image = gt_image[:, :, 0:2]/255

    return image, gt_image
```

I want to adapt this function to the multi-class case, but it wasn't enough to change the line to: 
```
gt_image = gt_image[:, :, :-1]/255
```
So I must be misunderstanding something.

**Comment by MarvinTeichmann** [comment]
> What is the purpose of gt_zero here? 

scipy.misc.imresize requires the input to have one, three or four channel. gt_image has two channels. So gt_zero is used to pad the image.

> And what is the purpose of dividing the resized image pixels by 255

The input `gt_image` consists of values 0 and 1. scipy.misc.imresize however converts this to 0 and 255. This line brings the labels back into the desired scale.

> I want to adapt this function to the multi-class case

You will need to slice the gt_image into tensors having only one, three or four channels (in order to use  scipy.misc.imresize). You could also try using [this](https://docs.scipy.org/doc/scipy-0.19.0/reference/generated/scipy.interpolate.interpn.html) function with method=“nearest”.

**Comment by MarvinTeichmann** [comment]
FYI: Karpathy is not happy about how scipy.misc.imresize magically changes image values eather:

https://github.com/scipy/scipy/issues/4458#issuecomment-269067103

**Comment by villanuevab** [comment]
Thank you so much! Your answers provided a lot of insight into the issue. My code is running as expected now.
